<?php

function recyclebin_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'delete') && method_exists($form_state->getFormObject(), 'getEntity')) {
    $entity = $form_state->getFormObject()->getEntity();
    $entity_type = $entity->getEntityType();
    if ($entity_type == 'node') {
      $form['description'] = array(
            '#markup' => t('The @entity %label will be moved to the trash.', ['@entity' => $entity_type->get('label'), '%label' => $entity->label()]),
          );
    }
  }
}